CREATE TABLE IF NOT EXISTS users(
id BIGINT NOT NULL PRIMARY KEY,
username VARCHAR(45) NULL,
password VARCHAR(45) NULL,
enabled INT NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities(
id BIGINT NOT NULL PRIMARY KEY,
username VARCHAR(45) NULL,
authority VARCHAR(45) NULL
);